[package]
name = "pi"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "pi: a terminal coding agent"

repository = "https://github.com/gitduk/pi-rs"
[[bin]]
name = "pi"
path = "src/main.rs"

[dependencies]
pi-core.workspace = true
pi-store.workspace = true
ui.workspace = true
agent.workspace = true
llm.workspace = true
tool.workspace = true
anyhow.workspace = true
clap.workspace = true
tokio-util.workspace = true
tracing.workspace = true
tokio.workspace = true
